prompt_templates = {
    "Modern": "Photo of a modern-style ({room}) with sleek built-in bookshelves, wall-mounted televisions, streamlined low-profile furniture, vibrant indoor plants, high-end designer lighting fixtures, ergonomic chairs, minimalist and functional coffee tables. Features clean architectural geometry, smart integrated storage, open floor plan with floor-to-ceiling windows, and a neutral base color palette with bold accent pieces. Includes sustainable premium materials, smart home automation, and seamless furniture integration. Architectural photography, ultra-sharp focus, cinematic wide-angle lens, perfect lighting balance (natural + artificial), raytraced reflections, realistic depth of field, ultra-detailed textures, hyperreal material rendering, perfect shadows, 32k resolution, photorealism.",

    "Scandinavian": "Photo of a Scandinavian-style ({room}) with pale wood furniture, cozy textiles, pendant lighting, woven rugs, floating shelves, and ergonomic seating. Includes hygge details, soft neutral colors, birch and pine accents, minimalist decoration, and functional simplicity. Large windows for daylight, soft indirect lighting, indoor greenery. Cinematic soft-focus lens, bright daylight atmosphere, ultra-detailed natural textures, hyperreal surfaces, raytraced shadows, photorealism, 32k resolution.",

    "Minimalist": "Photo of a minimalist-style ({room}) with low-profile modular sofa, essential ergonomic seating, selected greenery, clean floating furniture, monochrome palette with accent color, hidden smart storage. Architecture with negative space, clean unbroken lines, light wood or concrete floors, maximized sunlight. Architectural photography, shallow depth of field, ultra-sharp details, raytraced materials, realistic shadows, cinematic tone, photorealistic rendering, 32k resolution.",

    "Boho": "Photo of a bohemian-style ({room}) with vintage layered furniture, macramé details, mixed global textiles, large leafy plants, eclectic shelves, handcrafted items, warm earthy tones. Natural light filtering through sheer curtains, asymmetrical design layout, vibrant color pops, artisanal texture. Golden hour lighting, warm shadows, lens flare, ultra-detailed boho elements, raytraced materials, cinematic mood, 32k photorealism.",

    "Industrial": "Photo of an industrial-style ({room}) with exposed brick walls, reclaimed wood surfaces, concrete flooring, steel fixtures, loft-style high ceilings, visible ductwork, dark color palette, leather vintage sofas. Includes metal shelving and factory-inspired lighting. HDR architectural photography, deep shadows, raytraced metal and concrete, moody ambient light, hyperreal detail rendering, 32k resolution, photorealism.",

    "Vintage": "Photo of a vintage-style ({room}) with antique wood furniture, retro accessories, warm patterned textiles, classical lighting fixtures, ornate mirrors, decorative shelves, and nostalgic palette. Includes historical style details, aged surfaces, brass or bronze accents, layered historical character. Warm nostalgic lighting, shallow depth of field, ultra-detailed craftsmanship, raytraced vintage textures, cinematic focus, photorealism, 32k resolution.",

    "Coastal": "Photo of a coastal-style ({room}) with linen-covered furniture, nautical elements, whitewashed wood, sea glass color palette, driftwood accents, woven rugs, marine-themed artwork, large sunlit windows. Open, airy layout, relaxed furnishings. Bright seaside lighting, clear natural daylight, lens flare, ultra-real water-inspired textures, soft blue tones, cinematic coastal photography, photorealism, 32k resolution.",

    "Gaming": "Photo of a gaming-style ({room}) with RGB-lit ergonomic desk, ultra-wide monitor setup, ambient lighting control, immersive sound insulation, comfortable gaming chair, neon wall elements, display shelves for collectibles. Mood lighting in purple, red and blue, blackout curtains, tech-focused design, acoustic wall panels. Cinematic RGB glow, sharp tech detail, hyperreal materials, screen reflections, 32k resolution, photorealism.",

    "Neoclassic": "Photo of a neoclassical-style ({room}) with column-inspired structures, symmetrical furniture layout, gold-accented lighting, marble floors, classical wall moldings, grand lighting pieces, refined décor elements. Balanced harmony, historical motifs, rich fabrics. Dramatic lighting contrast, raytraced marble and gold, ultra-detailed ornamentation, shallow focus, cinematic mood, photorealism, 32k resolution.",

    "Luxury": "Photo of a luxury-style ({room}) with custom designer furniture, artisan finishes, crystal chandeliers, soft velvet textures, marble or stone flooring, museum-grade lighting, curated artworks. Seamless integration of smart systems, symmetrical spatial composition, rich neutral palette with gold or black accents. Hyperreal luxury surfaces, 32k resolution, architectural photography, raytraced reflections, cinematic atmosphere, photorealism."
}
