# fly.toml app configuration file generated for backendfffff on 2025-05-03T13:06:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backendfffff'
primary_region = 'nrt'

[build]

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"
  REPLICATE_API_TOKEN = "r8_7IfUadQSkl3N2PGZR4HWswF3J55FUfZ0TUiQj"
  CLOUDINARY_CLOUD_NAME = "dbgwyc5o4"
  CLOUDINARY_API_KEY = "873135915466665"
  CLOUDINARY_API_SECRET = "uptiwp7Chfu1Z0SkUaC-iHaSVUE"
  ALLOWED_ORIGINS = "*"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "data"
  destination = "/app/uploads"
